
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wixqqqpuhafdshgizoqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeHFxcXB1aGFmZHNoZ2l6b3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjQ4MDgsImV4cCI6MjA2MDkwMDgwOH0.82fbgA-zzYl6eXdEaqfq8varNS68_nKjYnZyBkU2Iy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create typed client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
